version: 2.1

variables:
  - &workspace /home/circleci/project

jobs:
  checkout_repository:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - persist_to_workspace:
          root: *workspace
          paths:
            - .

  test:
    docker:
      - image: circleci/python:3.8
    working_directory: *workspace
    steps:
      - attach_workspace:
          at: *workspace
      - run:
          name: Run unit tests
          command: |
            make test

  build:
    docker:
      - image: circleci/python:3.8
    working_directory: *workspace
    steps:
      - attach_workspace:
          at: *workspace
      - run:
          name: Build docker image
          command: |
            make build

  bump:
    docker:
      - image: circleci/golang:1.13
    working_directory: *workspace
    steps:
      - attach_workspace:
          at: *workspace
      - run:
          name: Increment version tag
          command: |
            go get github.com/tcnksm/ghr
            COMMIT_MSG=$(git log -1 --pretty=%B | cat)
            SCOPE=
            if [[ echo "${COMMIT_MSG,,}" =~ ^.*\#major.*$ ]]; then
              SCOPE=major
            elif [[ echo "${COMMIT_MSG,,}" =~ ^.*\#minor.*$ ]]; then
              SCOPE=minor
            else
              SCOPE=patch
            fi
            VERSION=$(./scripts/semtag final -s ${SCOPE} -o)
            ghr -t ${GITHUB_PAT} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION}
            echo ${VERSION} > VERSION
      - persist_to_workspace:
          root: *workspace
          paths:
            - .

  publish:
    docker:
      - image: circleci/python:3.8
    working_directory: *workspace
    steps:
      - attach_workspace:
          at: *workspace
      - run:
          name: Publish Docker image to ECR
          command: |
            make publish

  deploy_staging:
    docker:
      - image: circleci/python:3.8
    working_directory: *workspace
    steps:
      - run: echo "This step deploys to staging environment"

  deploy_production:
    docker:
      - image: circleci/python:3.8
    working_directory: *workspace
    steps:
      - run: echo "This step deploys to production environment"

workflows:
  version: 2

  test_branch:
    jobs:
      - checkout_repository
      - test:
          requires:
            - checkout_repository

  deploy_release:
    jobs:
      - checkout_repository:
          filters:
            branches:
              only: /dev/
      - bump:
          requires:
            - checkout_repository
      - build:
          requires:
            - bump
      - publish:
          requires:
            - build
      - deploy_staging:
          requires:
            - publish
      - hold_deploy_production:
          type: approval
          requires:
            - publish
      - deploy_production:
          requires:
            - hold_deploy_production
