version: 2.1

variables:
  - &workspace /home/circleci/project

jobs:
  checkout_repository:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - persist_to_workspace:
          root: *workspace
          paths:
            - .

  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - attach_workspace:
          at: *workspace
      - run:
          name: Run unit tests
          command: |
            make test

  release:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: *workspace
      - run: 
          name: Install versioning and release tool
          command: |
           sudo npm install -g standard-version
      - run:
          name: Create new release
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

            git config user.email "engineering@nav.sh"
            git config user.name "CircleCI"
            npx standard-version --no-verify 
            git push --follow-tags origin dev

            cat CHANGELOG.md
            VERSION=$(git describe --tags --abbrev=0)
            echo ${VERSION} > VERSION
      - persist_to_workspace:
          root: *workspace
          paths:
            - .

  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - attach_workspace:
          at: *workspace
      - run:
          name: Build docker image
          command: |
            VERSION=$(cat VERSION) make build

  publish:
    docker:
      - image: circleci/python:3.8
    working_directory: *workspace
    steps:
      - attach_workspace:
          at: *workspace
      - run:
          name: Publish Docker image to ECR
          command: |
            VERSION=$(cat VERSION) make publish

  deploy_staging:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: echo "This step deploys to staging environment"

  deploy_production:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: echo "This step deploys to production environment"

workflows:
  version: 2

  test_branch:
    jobs:
      - checkout_repository:
          filters:
            branches:
              ignore: /dev/
      - test:
          requires:
            - checkout_repository

  deploy_release:
    jobs:
      - checkout_repository:
          filters:
            branches:
              only: /dev/
      - release:
          requires:
            - checkout_repository
      - build:
          requires:
            - release
      - publish:
          requires:
            - build
      - deploy_staging:
          requires:
            - publish
      - hold_deploy_production:
          type: approval
          requires:
            - publish
      - deploy_production:
          requires:
            - hold_deploy_production
