version: 2.1

orbs:
  semver-orb: tv2norge/semver-orb@0.0.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            make test

  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            make build

  publish:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Publish Docker image to ECR
          command: |
            make publish

  deploy_staging:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: echo "This step deploys to staging environment"

  deploy_production:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: echo "This step deploys to production environment"

workflows:
  version: 2

  test_branch:
    jobs:
      - test

  deploy_release:
    jobs:
      - semver-orb/bump
      - build:
          requires:
            - semver-orb/bump
      - publish:
          requires:
            - build
      - deploy_staging:
          requires:
            - publish
      - hold_deploy_production:
          type: approval
          requires:
            - publish
      - deploy_production:
          requires:
            - hold_deploy_production
