version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: echo "This step runs test suite"
      - run: sleep 5
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: echo "This step build docker images"
      - run: sleep 5
  test_build:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: echo "This step tests the docker image"
  deploy_staging:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: echo "This step deploys to staging environment"
  deploy_production:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: echo "This step deploys to production environment"

workflows:
  version: 2
  test_branch:
    jobs:
      - test
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
      - test_build:
          requires:
            - build
      - deploy_staging:
          requires:
            - test_build
      - hold_deploy_production:
          type: approval
          requires:
            - test_build
      - deploy_production:
          requires:
            - hold_deploy_production
